#--- JJK 10.1.2025
Vagrant.configure("2") do |config|

  ENV['VAGRANT_DEFAULT_PROVIDER'] = 'vmware_desktop'
  
    config.vm.boot_timeout = 600   # this stuff is from template
    config.vm.graceful_halt_timeout = 600
    config.winrm.retry_limit = 30
    config.winrm.retry_delay = 10

  boxes = [
    { 
      name: "GOAD-DC01",
      ip: "192.168.56.10",
      box: "StefanScherer/windows_2019",
      box_version: "2021.05.15",
      os: "windows",
      cpus: 2,
      mem: 3000
    },
	{ 
      name: "GOAD-DC02",
      ip: "192.168.56.11",
      box: "StefanScherer/windows_2019",
      box_version: "2021.05.15",
      os: "windows",
      cpus: 2,
      mem: 3000
    },
	{
      name: "GOAD-DC03",
      ip: "192.168.56.12",
      box: "StefanScherer/windows_2016",
      box_version: "2017.12.14",
      os: "windows",
      cpus: 2,
      mem: 3000
    },
	{
      name: "GOAD-SRV2",
      ip: "192.168.56.22",
      box: "StefanScherer/windows_2019",
      box_version: "2021.05.15",
      os: "windows",
      cpus: 2,
      mem: 6000
    },
	{
      name: "GOAD-SRV3",
      ip: "192.168.56.23",
      box: "StefanScherer/windows_2016",
      box_version: "2019.02.14",
      os: "windows",
      cpus: 2,
      mem: 5000
#    },
#    {
#      name: "GOAD-BUILDER",  # This is if you wanted to Ubuntu server box
#      ip: "192.168.56.100",
#
#      box: "bento/ubuntu-22.04",
#      cpus: 2,
#      mem: 2048,
#      os: "linux"
    }

  ]

  boxes.each do |opts|
    config.vm.define opts[:name] do |vm|
	  vm.vm.box = opts[:box]
      vm.vm.box_version = opts[:box_version]
      vm.vm.hostname = opts[:name] # This sets the VM hostname inside the OS
      # issues/49
      vm.vm.synced_folder '.', '/vagrant', disabled: true
      vm.vm.network "private_network", ip: opts[:ip]
      
      vm.vm.provider :vmware_desktop do |v|
         v.vmx["memsize"] = opts[:mem].to_s
         v.cpus = opts[:cpus]
         # jjk 9.18.25
         # v.force_vm_license = "workstation" #force the license for some vagrant plugin issues
         v.vmx["ethernet0.pcislotnumber"] = "192"  # Fix warning
         v.vmx["ethernet1.pcislotnumber"] = "224"  # Fix warning
      end
      
      # Optional shell provisioner - JJK, from template
      if opts[:os] == "windows"
        vm.vm.guest = :windows
        vm.vm.communicator = "winrm"
        vm.vm.provision :shell, :path => "G:/GOAD/vagrant/Install-WMF3Hotfix.ps1", privileged: false
        vm.vm.provision :shell, :path => "G:/GOAD/vagrant/ConfigureRemotingForAnsible.ps1", privileged: false

        # fix for vmware static ip
        vm.vm.provision :shell, :path => "G:/GOAD/vagrant/fix_ip.ps1", privileged: true, args: opts[:ip]
        # also enable ping response
        vm.vm.provision :shell, :path => “G:/GOAD/vagrant/fix_ping.ps1”, privileged: true
        
      else
        vm.vm.communicator = "ssh"
      end
      
    end
  end
end
